# Generated by Django 3.2.1 on 2021-05-06 03:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.IntegerField(unique=True)),
                ('subject_1', models.CharField(choices=[['English', 'English']], max_length=16)),
                ('subject_2', models.CharField(choices=[['Maths', 'Maths']], max_length=16)),
                ('subject_3', models.CharField(choices=[['Science', 'Science']], max_length=16)),
                ('subject_4', models.CharField(choices=[['Tamil', 'Tamil'], ['French', 'French'], ['Hindi', 'Hindi']], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maths', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('science', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('elective', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add', to='ap1.student', unique=True)),
            ],
        ),
    ]
