# Generated by Django 3.2.1 on 2021-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_4',
            field=models.CharField(max_length=12),
        ),
    ]
